### ISSUE TITLE
MapTweaks+

### ISSUE THREAD

**Issue by GittyAkif** [creepycats/gatoclient#30]
The Addon MapTweaks+ is been removed. May I know the reason? Are we gonna have a better addon? or will we get the addon back?

**Comment by Sapphire-code** [comment]
The addon was removed due to Gato suspecting that the addon may get players banned due to using it. He doesn't wanna risk people getting locked.
![image](https://user-images.githubusercontent.com/85494077/233973835-6e05ecfb-7c7b-4c25-b93f-b7048f311225.png)

**Comment by gatodevelowoper** [comment]
Additionally, Old Methods used in Maptweaks have been patched.
