### ISSUE TITLE
Alt Tab

### ISSUE THREAD

**Issue by axoni1** [creepycats/gatoclient#31]
Whenever i alt tab to switch tabs many tabs of the game open and i cant close even 1 or the whole game crashes

**Comment by Sapphire-code** [comment]
> Whenever i alt tab to switch tabs many tabs of the game open and i cant close even 1 or the whole game crashes

Can you provide your specs? This really looks like an issue with your PC hardware maybe being under powered.

**Comment by axoni1** [comment]
Amd ryzen 5600g 32gb ram 3060 gigabyte gaming x b550 On Mon, Apr 24, 2023 at 6:49 AM SapphireKR ***@***.***> wrote:

Whenever i alt tab to switch tabs many tabs of the game open and i cant close even 1 or the whole game crashes

Can you provide your specs? This really looks like an issue with your PC hardware maybe being under powered.

**Comment by Sapphire-code** [comment]
This seems like an issue with krunker itself, since a lot of people have it. Try to reinstall gatoclient and see if the issue stops. If it doesn't then close all heavy weight programs you may be running in the background.

btw don't reply with email, you might leak your email address!

**Comment by gatodevelowoper** [comment]
Won't try fixing, seems like an issue I cannot personally troubleshoot and may be specific to your hardware.
